import "./globals.css";
import { montserrat, lato, open_Sans } from "./fonts";
// import { SessionProvider } from "next-auth/react";

export const metadata = {
  title: "Board.",
  description: "Generated by create next app",
};

export default function RootLayout({ children, pageProps }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${lato.variable} ${open_Sans.variable} h-screen text-base font-montserrat font-medium bg-main`}
      >
        {/* <SessionProvider session={pageProps.session}> */}
        {children}
        {/* </SessionProvider> */}
      </body>
    </html>
  );
}
